services:
  kmip-server-dsm:
    build:
      context: .
    ports:
      - 5696:5696
    volumes:
      - type: bind
        source: ./state
        target: /var/lib/state
      - type: bind
        source: ./certs
        target: /var/lib/certs
